code --install-extension asvetliakov.vscode-neovim
code --install-extension bufbuild.vscode-buf
code --install-extension cssho.vscode-svgviewer
code --install-extension dbaeumer.vscode-eslint
code --install-extension dracula-theme.theme-dracula
code --install-extension esbenp.prettier-vscode
code --install-extension groogle.termin-all-or-nothing
code --install-extension mechatroner.rainbow-csv
code --install-extension mikestead.dotenv
code --install-extension naumovs.color-highlight
code --install-extension Orta.vscode-jest
code --install-extension Orta.vscode-jest
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension waderyan.gitblame
code --install-extension will-wow.vscode-alternate-file
code --install-extension wix.vscode-import-cost
