code --install-extension Angular.ng-template
code --install-extension CraigMaslowski.erb
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension JakeBecker.elixir-ls
code --install-extension Orta.vscode-jest
code --install-extension Vans.haskero
code --install-extension castwide.solargraph
code --install-extension cssho.vscode-svgviewer
code --install-extension dbaeumer.vscode-eslint
code --install-extension dracula-theme.theme-dracula
code --install-extension eg2.tslint
code --install-extension esbenp.prettier-vscode
code --install-extension freebroccolo.reasonml
code --install-extension hackwaly.ocaml
code --install-extension hoovercj.haskell-linter
code --install-extension jcanero.hoogle-vscode
code --install-extension justusadam.language-haskell
code --install-extension mechatroner.rainbow-csv
code --install-extension mikestead.dotenv
code --install-extension monofon.hindent-format
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension natewallace.angular2-inline
code --install-extension noku.rails-run-spec-vscode
code --install-extension patrys.vscode-code-outline
code --install-extension pflannery.vscode-versionlens
code --install-extension rebornix.Ruby
code --install-extension sianglim.slim
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tomoki1207.pdf
code --install-extension vscodevim.vim
code --install-extension waderyan.gitblame
code --install-extension will-wow.vscode-alternate-file
code --install-extension will-wow.vscode-open-buffers
code --install-extension xabikos.ReactSnippets
